.nh
.TH "CUKES-VHS" "1" "Feb 2026" "cukes-vhs" "cukes-vhs Manual"

.SH NAME
cukes-vhs-completion - Generate shell completion scripts


.SH SYNOPSIS
\fBcukes-vhs completion [bash|zsh|fish|powershell]\fP


.SH DESCRIPTION
Generate shell completion scripts for cukes-vhs.

.PP
To load completions:

.PP
Bash:
  $ source <(cukes-vhs completion bash)
  # To load completions for each session, execute once:
  # Linux:
  $ cukes-vhs completion bash > /etc/bash_completion.d/cukes-vhs
  # macOS:
  $ cukes-vhs completion bash > $(brew --prefix)/etc/bash_completion.d/cukes-vhs

.PP
Zsh:
  # If shell completion is not already enabled in your environment,
  # you will need to enable it. You can execute the following once:
  $ echo "autoload -U compinit; compinit" >> ~/.zshrc
  # To load completions for each session, execute once:
  $ cukes-vhs completion zsh > "${fpath[1]}/_cukes-vhs"
  # You will need to start a new shell for this setup to take effect.

.PP
Fish:
  $ cukes-vhs completion fish | source
  # To load completions for each session, execute once:
  $ cukes-vhs completion fish > ~/.config/fish/completions/cukes-vhs.fish

.PP
PowerShell:
  PS> cukes-vhs completion powershell | Out-String | Invoke-Expression
  # To load completions for every new session, run:
  PS> cukes-vhs completion powershell > cukes-vhs.ps1
  # and source this file from your PowerShell profile.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH SEE ALSO
\fBcukes-vhs(1)\fP


.SH HISTORY
25-Feb-2026 Auto generated by spf13/cobra
